language: node_js
node_js:
  - 10

install: npm i
cache: npm

jobs:
  include:
    - stage: Test
      script: npm run lint
      name: "Lint"
    - script: npm run build
      name: "Build"
    
    - stage: Deploy
      script: skip
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true
